server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
   registry-fetch-interval-seconds: 15
   disable-delta: true
  server:
   response-cache-update-interval-ms: 10000
    peer-node-read-timeout-ms: 400
    peer-node-connect-timeout-ms: 400