spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "482158751917-d2btptffp0kqve7h30fkeib75sptuihc.apps.googleusercontent.com"
            client-secret: "d6mRR5N40LOuRKptcg9Co_an"
            scope:
              - email
              - profile

          naver:
            client-id: "E9ePtC22gVnRUatqzahv"
            client-secret: "0wGchWP6EP"
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: "authorization_code"
            scope:
              - name
              - email
              - profile_image
            client-name: "Naver"

          kakao:
            client-id: "43a19762f4a90f7e52c062fc30db754f"
            client-secret: "Qx8ve5xffhhDN2Atu82ufzlMAkarQh2Z"
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: "authorization_code"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: POST
            client-name: "Kakao"

        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: "response"

          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: "id"